### ISSUE TITLE
按照test-address.txt格式导入数据报错

### ISSUE THREAD

**Issue by suntxy** [liuzhibin-cn/address-semantic-search#1]
$ bin/imp-address.sh test-addresses.txt
Start importing addresses ...log4j:WARN Continuable parsing error 63 and column 23
log4j:WARN 元素类型为 "log4j:configuration" 的内容必须匹配 "(renderer*,throwableRenderer?,appender*,plugin*,(category|logger)*,root?,(categoryFactory|loggerFactory)?)"。
2017-10-13 11:43:38.986::INFO:  jetty-7.0.0.pre5
2017-10-13 11:43:38.030::INFO:  Started SelectChannelConnector@0.0.0.0:8000
> 开始导入地址库
> 导入: 0，用时: 6.463s.

直接导入test-addresses.txt的数据， 报错。。

**Comment by suntxy** [comment]
报错原因：1. 源码日志文件配置有错误，替换成了我们内部默认配置，直接打印报错记录看出问题。
2. 数据库插入数据，SQL语句的字段名称和建表脚本创建的字段名称不同。需要修改表字段名称。

**Comment by zhile005** [comment]
怎么解决的？
nohup: ignoring input
log4j:WARN Continuable parsing error 63 and column 23
log4j:WARN 元素类型为 "log4j:configuration" 的内容必须匹配 "(renderer*,throwableRenderer?,appender*,plugin*,(category|logger)*,root?,(categoryFactory|loggerFactory)?)"。
一月 30, 2021 7:16:36 下午 org.apache.tomcat.jdbc.pool.ConnectionPool init
严重: Unable to create initial connections of pool.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:741)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:57)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1663)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:662)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:352)
